### ISSUE TITLE
Train VGG19

### ISSUE THREAD

**Issue by lijun2005** [Fuzzy-sh/WA-SRGAN#1]
Hello! I have read your paper ,and you did a good job! Could you please tell me how your VGG19 model was trained and where weights or VGG19.pth of VGG19 is?

**Comment by Fuzzy-sh** [comment]
Hello @lijun2005,

Thank you for your comment. I utilized images from the BreaKHis database, which were resized to 256×256×3 for optimal training of the VGG-19 model.

I've made an update to the repository, and you can now find the link to the VGG.pth file there. If you have any additional questions or need further information, please don't hesitate to reach out.

**Comment by lijun2005** [comment]
OK，thank you for taking time out of your busy schedule to reply to my issue! Thanks a lot!



---Original---
From: ***@***.***&gt;
Date: Fri, Sep 29, 2023 04:20 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Fuzzy-sh/WA-SRGAN] Train VGG19 (Issue #1)




 
Hello @lijun2005,
 
Thank you for your comment. I utilized images from the BreaKHis database, which were resized to 256×256×3 for optimal training of the VGG-19 model.
 
I've made an update to the repository, and you can now find the link to the VGG.pth file there. If you have any additional questions or need further information, please don't hesitate to reach out.

**Comment by lijun2005** [comment]
emm...，Can you tell me if you hadnormalized the input image data when you trained VGG19?Is the input image pixel value scaled between 0 and 1 or between 0 and 255? I would be very grateful if you assist and answer me at your earliest convenience.

**Comment by lijun2005** [comment]
And When you feed the high-resolution images generated by the generator and the ground truth into VGG19 to calculate the loss, what is the pixel value range for them? Is it 0-1 or 0-255?

**Comment by Fuzzy-sh** [comment]
Hi @lijun2005 ; 

Thank you for your message. You can find answers to all of your questions in the "Two-Classifications" folder within the following GitHub repository: [Breast-Cancer-Classification](https://github.com/Fuzzy-sh/Breast-Cancer-Classification). Please take a look at VGG19_Breakhis_Classification.ipynb file in this folder.

Additionally, the paper related to this work is available there, which provides detailed information on how the model was trained and the methodology used.

I hope you find this information helpful for your inquiry. If you have any further questions or need additional assistance, please don't hesitate to ask.
