### ISSUE TITLE
I can't find which library the  “quantize”  function belongs to.

### ISSUE THREAD

**Issue by wangbiao0** [Fuzzy-sh/WA-SRGAN#2]
Hi, firstly thank you very much for your excellent work.
I'm having some insurmountable problems reproducing your work.
In your project
WA_SRGAN-with-Weight_norm->1-WA-SRGAN_256_x4_WN.ipynb   
This part of the code:
```
# Trianing, and validating the WA-SRGAN model 
......
if model==‘wdsr’.
          sr_quantize=quantize(sr,rgb_range)
          mse = ((sr_quantize - hr) ** 2).data.mean()
          valing_results[‘mse’] += mse.item()
          psnr = 10 * log10(255.0/(valing_results[‘mse’] / valing_results[‘valing_num’]))
......
```
I can't find the package that quantize belongs to, I have a problem with ‘unresolved reference to “quantize”’.
Can you tell me where to import ‘quantize’ from?

**Comment by Fuzzy-sh** [comment]
Hi @lk-wang, 
Thanks for reaching out. It seems like some parts were missing. I have updated the requested part. 
Please reach out if you have further inquiries. 
Thanks.
